### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by ruedigergad** [wojciech-graj/TermGL#1]
Hi,

thanks a lot for sharing this.
It's a very nice project.

I built a simple "fun"/"toy" application that uses TermGL.
My application connects to some other Open Source project of mine via a Message-oriented Middleware (MoM) and renders data received from the MoM in 3D in the terminal via TermGL.

I would like to share this application as Open Source on GitHub as well.
To properly give credit to TermGL, it would be great if there was some information about the TermGL license.
Is it possible for you to add license information to TermGL?

Thanks in advance and cheers,
Ruediger

**Comment by wojciech-graj** [comment]
Hey, thanks for using TermGL! It's always nice to write code which is used be others. I'll add a license later today or tommorow.

**Comment by ruedigergad** [comment]
Thanks a lot for adding the license file.
Here is the project I built on top of TermGL: https://github.com/ruedigergad/parTTYcles
I wrote a brief blog post that includes parTTYcles as well: https://ruedigergad.com/2021/08/23/polyglot-messaging-integration-for-fun/
Thanks again for implementing TermGL and for sharing it. :)
