### ISSUE TITLE
Tutorials for python?

### ISSUE THREAD

**Issue by therealjr** [wojciech-graj/TermGL#10]
Are there any tutorials for python? I'm trying to implement a pretty complex game using termgl but I cannot get some basic things to work. I have used help(object) to describe the methods and attributes contained within the classes, but I still would like some kind of examples.

**Comment by therealjr** [comment]
Thank you very much. I really love what you made!

**Comment by wojciech-graj** [comment]
I updated pyTermGL to use the newest version of TermGL, and you can find the tutorial here: https://github.com/wojciech-graj/pyTermGL/blob/master/TUTORIAL.md
And the API reference here: https://wojciech-graj.github.io/pyTermGL/termgl.html

**Comment by therealjr** [comment]
Hey thank you for putting in the time and effort into your tutorial. I think it contains some errors though.

For instance, 
import termgl as tgl

ctx = tgl.TGL(40, 24)
ctx.puts(0, 0, b"Hello World!", tgl.WHITE)
ctx.flush()
ctx.clear(tgl.Buffer.FRAME)

should be:

import termgl as tgl

ctx = tgl.TGL(40, 24, tgl.gradient_full)
ctx.puts(0, 0, b"Hello World!", tgl.Color.WHITE)
ctx.flush()
ctx.clear(tgl.Buffer.FRAME_BUFFER)


Additionally, when I tried to replicate one of your tutorials and reference tgl.PixelShader, I got that the method or class does not exist:

Help on module termgl:

NAME
    termgl - TermGL v0.1.2, Internal v1.2.1

DESCRIPTION
    Cython bindings for TermGL, the terminal-based graphics library.
    
    *tuple[int, int]* **VERSION**
       Major and Minor C TermGL version
    
    *termgl.Gradient* **gradient_min**
       Minimal gradient of length 10
    
    *termgl.Gradient* **gradient_full**
       Full gradient of length 70

CLASSES
    builtins.object
        Gradient
        TGL
        Transform
    enum.IntFlag(builtins.int, enum.Flag)
        Buffer
        Color
        Cull
        Setting
    
    class Buffer(enum.IntFlag)
     |  Buffer(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |  
     |  Buffers.
     |  Can use bitwise combination of all buffers as long as they have been enabled. *FRAME_BUFFER* is always enabled.
     |  
     |  * **FRAME_BUFFER**: frame buffer
     |  * **Z_BUFFER**: depth buffer
     |  * **OUTPUT_BUFFER**: output buffer allowing for just one print statement to flush. Much faster on most terminals
     |  
     |  Method resolution order:
     |      Buffer
     |      enum.IntFlag
     |      builtins.int
     |      enum.Flag
     |      enum.Enum
     |      builtins.object
     |  
     |  Data and other attributes defined here:
     |  
     |  FRAME_BUFFER = <Buffer.FRAME_BUFFER: 1>
     |  
     |  OUTPUT_BUFFER = <Buffer.OUTPUT_BUFFER: 2>
     |  
     |  Z_BUFFER = <Buffer.Z_BUFFER: 4>
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |  
     |  name
     |      The name of the Enum member.
     |  
     |  value
     |      The value of the Enum member.
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |  
     |  __members__
     |      Returns a mapping of member name->value.
     |      
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.
    
    class Color(enum.IntFlag)
     |  Color(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |  
     |  Colors and Font Modifiers.
     |  Can use bitwise combination of up to one **Text Color**, up to one **Background Color**, and any **Modifiers**.
     |  
     |  **Text Color**:
     |  
     |  * **BLACK**
     |  * **RED**
     |  * **GREEN**
     |  * **YELLOW**
     |  * **BLUE**
     |  * **PURPLE**
     |  * **CYAN**
     |  * **WHITE**
     |  
     |  **Background Color**:
     |  
     |  * **BLACK_BKG**
     |  * **RED_BKG**
     |  * **GREEN_BKG**
     |  * **YELLOW_BKG**
     |  * **BLUE_BKG**
     |  * **PURPLE_BKG**
     |  * **CYAN_BKG**
     |  * **WHITE_BKG**
     |  
     |  **Modifier**:
     |  
     |  * **HIGH_INTENSITY**
     |  * **HIGH_INTENSITY_BKG**
     |  * **BOLD**
     |  * **UNDERLINE**
     |  
     |  Method resolution order:
     |      Color
     |      enum.IntFlag
     |      builtins.int
     |      enum.Flag
     |      enum.Enum
     |      builtins.object
     |  
     |  Data and other attributes defined here:
     |  
     |  BLACK = <Color.BLACK: 0>
     |  
     |  BLUE = <Color.BLUE: 4>
     |  
     |  BLUE_BKG = <Color.BLUE_BKG: 64>
     |  
     |  BOLD = <Color.BOLD: 256>
     |  
     |  CYAN = <Color.CYAN: 6>
     |  
     |  CYAN_BKG = <Color.CYAN_BKG: 96>
     |  
     |  GREEN = <Color.GREEN: 2>
     |  
     |  GREEN_BKG = <Color.GREEN_BKG: 32>
     |  
     |  HIGH_INTENSITY = <Color.HIGH_INTENSITY: 8>
     |  
     |  HIGH_INTENSITY_BKG = <Color.HIGH_INTENSITY_BKG: 128>
     |  
     |  PURPLE = <Color.PURPLE: 5>
     |  
     |  PURPLE_BKG = <Color.PURPLE_BKG: 80>
     |  
     |  RED = <Color.RED: 1>
     |  
     |  RED_BKG = <Color.RED_BKG: 16>
     |  
     |  UNDERLINE = <Color.UNDERLINE: 512>
     |  
     |  WHITE = <Color.WHITE: 7>
     |  
     |  WHITE_BKG = <Color.WHITE_BKG: 112>
     |  
     |  YELLOW = <Color.YELLOW: 3>
     |  
     |  YELLOW_BKG = <Color.YELLOW_BKG: 48>
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |  
     |  name
     |      The name of the Enum member.
     |  
     |  value
     |      The value of the Enum member.
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |  
     |  __members__
     |      Returns a mapping of member name->value.
     |      
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.
    
    class Cull(enum.IntFlag)
     |  Cull(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |  
     |  Triangle culling options.
     |  Must use bitwise combination of one **Face** and one **Winding**.
     |  
     |  **Face**:
     |  
     |  * **BACK**
     |  * **FRONT**
     |  
     |  **Winding**:
     |  
     |  * **CW**
     |  * **CCW**
     |  
     |  Method resolution order:
     |      Cull
     |      enum.IntFlag
     |      builtins.int
     |      enum.Flag
     |      enum.Enum
     |      builtins.object
     |  
     |  Data and other attributes defined here:
     |  
     |  BACK = <Cull.BACK: 0>
     |  
     |  CCW = <Cull.CCW: 2>
     |  
     |  FRONT = <Cull.FRONT: 1>
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |  
     |  name
     |      The name of the Enum member.
     |  
     |  value
     |      The value of the Enum member.
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |  
     |  __members__
     |      Returns a mapping of member name->value.
     |      
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.
    
    class Gradient(builtins.object)
     |  Gradient(grad)
     |  
     |  Create a new character gradient used by drawing functions in TGL.
     |  
     |  :param bytes grad: Bytestring of characters in increasing intensity
     |  
     |  Methods defined here:
     |  
     |  __deinit__(self)
     |  
     |  __reduce__ = __reduce_cython__(...)
     |  
     |  __setstate__ = __setstate_cython__(...)
     |  
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |  
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  grad
     |      *Readonly* Gradient string
     |      
     |      :type: bytes
    
    class Setting(enum.IntFlag)
     |  Setting(value, names=None, *, module=None, qualname=None, type=None, start=1)
     |  
     |  Settings.
     |  Can use bitwise combination of all settings.
     |  
     |  * **Z_BUFFER**: depth buffer
     |  * **DOUBLE_CHARS**: square pixels by printing 2 characters per pixel
     |  * **CULL_FACE**: cull specified triangle faces in 3D
     |  * **OUTPUT_BUFFER**: output buffer allowing for just one print statement to flush. Much faster on most terminals
     |  * **PROGRESSIVE**: over-write previous frame instead of clearing screen. Elmininates strobing but requires call to tgl_clear_screen before drawing smaller image and after resizing terminal if terminal size was smaller than frame size
     |  
     |  Method resolution order:
     |      Setting
     |      enum.IntFlag
     |      builtins.int
     |      enum.Flag
     |      enum.Enum
     |      builtins.object
     |  
     |  Data and other attributes defined here:
     |  
     |  CULL_FACE = <Setting.CULL_FACE: 64>
     |  
     |  DOUBLE_CHARS = <Setting.DOUBLE_CHARS: 16>
     |  
     |  OUTPUT_BUFFER = <Setting.OUTPUT_BUFFER: 2>
     |  
     |  PROGRESSIVE = <Setting.PROGRESSIVE: 32>
     |  
     |  Z_BUFFER = <Setting.Z_BUFFER: 4>
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from enum.Enum:
     |  
     |  name
     |      The name of the Enum member.
     |  
     |  value
     |      The value of the Enum member.
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties inherited from enum.EnumMeta:
     |  
     |  __members__
     |      Returns a mapping of member name->value.
     |      
     |      This mapping lists all enum members, including aliases. Note that this
     |      is a read-only view of the internal mapping.
    
    class TGL(builtins.object)
     |  TGL(width, height, gradient)
     |  
     |  TermGL rendering context.
     |  
     |  :param int width:
     |  :param int height:
     |  :param termgl.Gradient gradient:
     |  :raises MemoryError:
     |  
     |  Methods defined here:
     |  
     |  __deinit__(self) -> 'None'
     |  
     |  __reduce__ = __reduce_cython__(...)
     |  
     |  __setstate__ = __setstate_cython__(...)
     |  
     |  camera(self, fov: 'float', near: 'float', far: 'float') -> 'None'
     |      camera(fov, near, far)
     |      
     |      Set the perspective projection matrix.
     |      
     |      :param float fov: field of view in radians
     |      :param float near: near plane distance
     |      :param float far: far plane distance
     |  
     |  clear(self, buffers: 'Buffer') -> 'None'
     |      clear(buffers)
     |      
     |      Clear buffers.
     |      
     |      :param termgl.Buffer buffers:
     |  
     |  cull_face(self, cull: 'Cull') -> 'None'
     |      cull_face(cull)
     |      
     |      Set face culling options.
     |      
     |      :param termgl.Cull cull:
     |  
     |  disable(self, settings: 'Setting') -> 'None'
     |      disable(settings)
     |      
     |      Disable settings.
     |      
     |      :param termgl.Setting settings:
     |  
     |  enable(self, settings: 'Setting') -> 'None'
     |      enable(settings)
     |      
     |      Enable settings.
     |      
     |      :param termgl.Setting settings:
     |      :raises MemoryError:
     |  
     |  flush(self) -> 'None'
     |      flush()
     |      
     |      Print framebuffer.
     |      
     |      :raises OSError:
     |  
     |  line(self, x0: 'int', y0: 'int', z0: 'float', i0: 'int', x1: 'int', y1: 'int', z1: 'float', i1: 'int', color: 'Color') -> 'None'
     |      line(x0, y0, z0, i0, x1, y1, z1, i1, color)
     |      
     |      Draw a line to the framebuffer.
     |      
     |      :param int x0:
     |      :param int y0:
     |      :param float z0: depth
     |      :param int i0: intensity [0..255]
     |      :param int x1:
     |      :param int y1:
     |      :param float z1: depth
     |      :param int i1: intensity [0..255]
     |      :param termgl.Color color:
     |  
     |  point(self, x: 'int', y: 'int', z: 'float', i: 'int', color: 'Color') -> 'None'
     |      point(x, y, z, i, color)
     |      
     |      Draw a point to the framebuffer.
     |      
     |      :param int x:
     |      :param int y:
     |      :param float z: depth
     |      :param int i: intensity [0..255]
     |      :param termgl.Color color:
     |  
     |  putchar(self, x: 'int', y: 'int', c: 'bytes', color: 'Color') -> 'None'
     |      putchar(x, y, c, color)
     |      
     |      Write a characer to the framebuffer.
     |      
     |      :param int x:
     |      :param int y:
     |      :param bytes c:
     |      :param termgl.Color color:
     |  
     |  puts(self, x: 'int', y: 'int', c: 'bytes', color: 'Color')
     |      puts(x, y, c, color)
     |      
     |      Write a string to the framebuffer.
     |      
     |      :param int x:
     |      :param int y:
     |      :param bytes c:
     |      :param termgl.Color color:
     |  
     |  triangle(self, x0: 'int', y0: 'int', z0: 'float', i0: 'int', x1: 'int', y1: 'int', z1: 'float', i1: 'int', x2: 'int', y2: 'int', z2: 'float', i2: 'int', color: 'Color', fill: 'bool' = False) -> 'None'
     |      triangle(x0, y0, z0, i0, x1, y1, z1, i1, x2, y2, z2, i2, color, fill=False)
     |      
     |      Draw a triangle to the framebuffer.
     |      
     |      :param int x0:
     |      :param int y0:
     |      :param float z0: depth
     |      :param int i0: intensity [0..255]
     |      :param int x1:
     |      :param int y1:
     |      :param float z1: depth
     |      :param int i1: intensity [0..255]
     |      :param int x2:
     |      :param int y2:
     |      :param float z2: depth
     |      :param int i2: intensity [0..255]
     |      :param termgl.Color color:
     |      :param bool fill:
     |  
     |  triangle3d(self, vertices: 'np.ndarray', intensity: 'np.ndarray', color: 'Color', fill: 'bool' = False) -> 'None'
     |      triangle3d(vertices, intensity, color, fill=False)
     |      
     |      Draw a 3D triangle to the framebuffer.
     |      
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(3,3)] vertices:
     |      :param numpy.ndarray[dtype=numpy.uint8, shape=(3)] intensity:
     |      :param termgl.Color color:
     |      :param bool fill:
     |  
     |  triangle3da(self, vertices: 'np.ndarray', intensities: 'np.ndarray', colors: 'np.ndarray', fill: 'np.ndarray', cnt: 'int') -> 'None'
     |      triangle3da(vertices, intensities, colors, fill, cnt)
     |      
     |      Draw an array of 3D triangles to the framebuffer.
     |      
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(cnt, 3, 3)] vertices:
     |      :param numpy.ndarray[dtype=numpy.uint8, shape=(cnt, 3)] intensities:
     |      :param numpy.ndarray[dtype=numpy.uint16, shape=(cnt)] colors:
     |      :param numpy.ndarray[dtype=numpy.bool, shape=(cnt)] fill:
     |      :param int cnt:
     |  
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |  
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  gradient
     |      *Readonly*
     |      
     |      :type: termgl.Gradient
     |  
     |  shader
     |      Shader function called during 3D rendering after projection and clipping, and before writing to framebuffer. Takes the triangle's vertices and the vertices' intensities as input, and these values can be changed by the function.
     |      
     |      :type: Callable[numpy.ndarray[dtype=numpy.float32, shape=(3,3)], numpy.ndarray[dtype=numpy.uint8, shape=(3)]] or None
     |  
     |  transform
     |      *Readonly* Internal transform applied before perspective projection. Comparable to view matrix.
     |      
     |      :type: termgl.Transform
    
    class Transform(builtins.object)
     |  Transform()
     |  
     |  3D Transformation using 4x4 matrices.
     |  Applied in order: rotation -> scale -> translation.
     |  
     |  :raises MemoryError:
     |  
     |  Methods defined here:
     |  
     |  __deinit__(self)
     |  
     |  __reduce__ = __reduce_cython__(...)
     |  
     |  __setstate__ = __setstate_cython__(...)
     |  
     |  apply(self, vin: 'np.ndarray', vout: 'np.ndarray') -> 'None'
     |      apply(vin, vout)
     |      
     |      Apply the result transformation to three points
     |      
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(3,3)] vin:
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(3,3)] vout:
     |  
     |  applya(self, vin: 'np.ndarray', vout: 'np.ndarray', cnt: 'int') -> 'None'
     |      apply(vin, vout, cnt)
     |      
     |      Apply the result transformation to an array of groups of three points
     |      
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(cnt, 3,3)] vin:
     |      :param numpy.ndarray[dtype=numpy.float32, shape=(cnt, 3,3)] vout:
     |      :param int cnt:
     |  
     |  calc_result(self) -> 'None'
     |      calc_result()
     |      
     |      Calculate the result matrix based on the translation, scale, and rotation matrices.
     |      Must be called prior to *apply* or *applya* if any matrices have changed.
     |  
     |  calc_rotation(self, x: 'float', y: 'float', z: 'float') -> 'None'
     |      calc_rotation(x, y, z)
     |      
     |      Calculate the rotation matrix
     |      
     |      :param float x:
     |      :param float y:
     |      :param float z:
     |  
     |  calc_scale(self, x: 'float', y: 'float', z: 'float') -> 'None'
     |      calc_scale(x, y, z)
     |      
     |      Calculate the scale matrix
     |      
     |      :param float x:
     |      :param float y:
     |      :param float z:
     |  
     |  calc_translation(self, x: 'float', y: 'float', z: 'float') -> 'None'
     |      calc_translation(x, y, z)
     |      
     |      Calculate the translation matrix
     |      
     |      :param float x:
     |      :param float y:
     |      :param float z:
     |  
     |  ----------------------------------------------------------------------
     |  Static methods defined here:
     |  
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |  
     |  result
     |      *Readonly* Result matrix obtained after multiplying rotation, scale, and translation matrices
     |      :type: numpy.ndarray[dtype=numpy.float32, shape=(4,4)]
     |  
     |  rotation
     |      Rotation matrix
     |      :type: numpy.ndarray[dtype=numpy.float32, shape=(4,4)]
     |  
     |  scale
     |      Scale matrix
     |      :type: numpy.ndarray[dtype=numpy.float32, shape=(4,4)]
     |  
     |  translation
     |      Translation matrix
     |      :type: numpy.ndarray[dtype=numpy.float32, shape=(4,4)]

FUNCTIONS
    __reduce_cython__(self)
    
    __setstate_cython__(self, __pyx_state)
    
    clear_screen() -> 'None'
        clear_screen()
        
        Clear the sceen.
    
    flush() -> 'None'
        flush()
        
        Flush stdout.
    
    get_console_size(screen_buffer: 'bool') -> 'Tuple[int, int]'
        get_console_size(screen_buffer)
        
        Get number of console columns and rows.
        
        :param bool screen_buffer: True for size of screen buffer, False for size of window. On UNIX, value is ignored and assumed True
        :returns: column and row count
        :rtype: tuple[int, int]
        :raises OSError:
    
    read(count: 'int') -> 'bytes'
        read(count: int)
        
        Read up to count bytes (characters) from raw terminal input without blocking.
        
        :param count: maximum number of bytes to read
        :type count: int
        :returns: input from stdin
        :rtype: bytes
        :raises OSError:
    
    set_console_size(col: 'int', row: 'int') -> 'None'
        set_console_size(col, row)
        
        Set console size.
        Only changes printable area and will not enlarge window if printable area extends beyond window.
        
        :param int col: number of columns
        :param int row: number of rows
        :raises OSError:

DATA
    Callable = typing.Callable
    Optional = typing.Optional
    Tuple = typing.Tuple
    VERSION = (1, 2)
    __test__ = {}
    gradient_full = <termgl.Gradient object>
    gradient_min = <termgl.Gradient object>

FILE
    /home/jonny/anaconda3/envs/termgl/lib/python3.8/site-packages/termgl.cpython-38-x86_64-linux-gnu.so

**Comment by therealjr** [comment]
I think the issue might be that pip is not installing the most recent version of termgl for pytermgl.

**Comment by wojciech-graj** [comment]
So that first snippet is correct, as I explained in this line

> For ease-of-use, PixFmt objects for indexed foreground colors are provided as tgl.WHITE, tgl.RED, etc.

You can install the newest version with `pip install termgl==0.2.1`

**Comment by therealjr** [comment]
Thanks
